export const darkTheme = {
  colors: {
    background: '#1a1a1a',
    card: '#2a2a2a',
    surface: '#2a2a2a',
    primary: '#ff6b35',
    secondary: '#4a4a4a',
    accent: '#4a4a4a',
    text: '#ffffff',
    textSecondary: '#b3b3b3',
    border: '#404040',
    error: '#ff4444',
    success: '#4caf50',
    warning: '#ff9800',
    info: '#2196f3',
    muted: '#4a4a4a',
    inputBackground: '#2a2a2a',
    inputBorder: '#404040',
    placeholder: '#b3b3b3',
    icon: '#ff6b35',
    tabInactive: '#b3b3b3',
    tabActive: '#ff6b35',
    // shadcn/ui compatible colors
    foreground: '#ffffff',
    cardForeground: '#ffffff',
    popover: '#2a2a2a',
    popoverForeground: '#ffffff',
    primaryForeground: '#ffffff',
    secondaryForeground: '#ffffff',
    mutedForeground: '#b3b3b3',
    accentForeground: '#ffffff',
    destructive: '#ff4444',
    input: '#2a2a2a',
    ring: '#ff6b35',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  borderRadius: 10.4,
  font: {
    regular: 'System',
    bold: 'System',
  },
};

export type Theme = typeof darkTheme; 